tcount: 1
offset: 16
data: 
    "0": [ 0.998861 ,-0.0437453, -0.0190292,   0.640182,
	-0.0228217, -0.0878983  ,-0.995868 ,  0.318734,
	 0.0418919 ,  0.995168 ,-0.0887966 ,   2.27643,
          0,0,0,1]
    "1": [ 0.999579,0.0111009,0.0267891,3.21075,
           0.028022,-0.132164,-0.990832,0.370414,
           -0.0074585,0.991166,-0.13242,3.76058,
          0,0,0,1]
    "2": [  0.9893 ,-0.1069,-0.0994 ,   0.6371,
          -0.0985, 0.0135 ,   -0.995 ,  -1.997,
          0.1077 , 0.9941, 0.00286 , 5.6575,
          0,0,0,1]
    "3": [  0.9893 ,-0.1069,-0.0994 ,   0.6371,
          -0.0985, 0.0135 ,   -0.995 ,  -1.997,
          0.1077 , 0.9941, 0.00286 , 5.6575,
          0,0,0,1]
    "4": [0.9949 ,-0.0963, 0.02925 ,   2.1511, 
          0.03194, 0.02654 ,   -0.9991 ,  -3.971,
          0.0954 , 0.995,  0.02948 ,  -3.5928,
          0,0,0,1]
    "5": [0.9949 ,-0.0963, 0.02925 ,   2.1511, 
          0.03194, 0.02654 ,   -0.9991 ,  -3.971,
          0.0954 , 0.995,  0.02948 ,  -3.5928,
          0,0,0,1]
    "6": [-0.0731 ,0.0184,-0.997 ,   -8.675, 
          -0.994, 0.0807 ,   0.0743 ,  3.861,
          0.0818 , 0.997,  0.0124 ,  -67.089,
          0,0,0,1]
    "7": [ -0.0731 ,0.0184,-0.997 ,   -8.675, 
          -0.994, 0.0807 ,   0.0743 ,  3.861,
          0.0818 , 0.997,  0.0124 ,  -67.089,
          0,0,0,1]
error:
    "0": [26,5,32,5]
    "1": [-4,3,-4,3]
    "2": [37.21,3.00,37.21,3.00]
    "3": [37.21,3.00,37.21,3.00]
    "4": [14.53,-4.42,14.53,-4.42]
    "5": [14.53,-4.42,14.53,-4.42]
    "6": [7.34,-8.38,7.34,-8.38]
    "7": [7.34,-8.38,7.34,-8.38]
