##net param
DeviceID: 0

MyselfNetIp: "192.168.2.99"

UpperNetIp: "192.168.2.200"
UpperNetPort: 9339
UpperNetBuad: 9600

LidarNetIp: "192.168.61.21"
LidarNetPort: 5000
LidarNetBuad: 9600
LidarDataSave: False


